# Ubuntu 이미지를 기반으로 시작
FROM ubuntu:latest

EXPOSE 6667

# 필요한 패키지 설치
RUN apt-get update && apt-get install -y \
    build-essential \
    libssl-dev \
    wget \
    inspircd \
    tcpflow \
    iproute2 \
    vim

# InspIRCd 설정 변경
WORKDIR /etc/inspircd/
RUN mkdir /var/run/inspircd

COPY inspircd.conf /etc/inspircd/inspircd.conf



# InspIRCd 실행

CMD ["sh", "-c", "inspircd --runasroot && tcpflow -i eth0 port 6667 -c"]
